; PlatformIO Project Configuration File
; ESP32-WROOM-32 dual-channel DAC signal generator

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed =921600

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.4
    adafruit/Adafruit BusIO @ ^1.16.2
